{{ if .Values.enabled }}
{{- if .Values.isRBAC }}
apiVersion: {{ .Values.apiVersions.clusterRole }}
kind: ClusterRole
metadata:
  name: {{ include "fluentd.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules: {{ toYaml .Values.clusterRole.rules | nindent 2 -}}
{{- end }}
{{ end }}