{{ if .Values.enabled }}
{{- if or .Values.daemonset.fluentdPrometheusConf .Values.windowsDaemonset.fluentdPrometheusConf }}
apiVersion: {{ .Values.apiVersions.configmap }}
kind: ConfigMap
metadata:
  name: {{ include "fluentd.fullname" . }}-monitoring
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: {{ .Values.k8sApp }}
data:
  prometheus.conf : {{ toYaml .Values.configmap.prometheus | indent 2 }}
{{- end }}
{{ end }}