apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "logzio-monitoring-operator.clusterRoleName" . }}
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups:
      - cache.logzio.com
    resources:
      - memcacheds
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
    verbs:
      - get
      - list
      - watch
      - update
  - apiGroups:
      - ""
    resources:
      - pods
      - nodes
      - endpoints
      - services
      - configmaps
    verbs:
      - get
      - list
      - watch