apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: memcacheds.cache.logzio.com
spec:
  group: cache.logzio.com
  names:
    kind: Memcached
    listKind: MemcachedList
    plural: memcacheds
    singular: memcached
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          description: Memcached is the Schema for the memcacheds API
          properties:
            spec:
              description: MemcachedSpec defines the desired state of Memcached
              properties:
                lastTimestamp:
                  description: Last timestamp the operator calculated the limits
                  type: string
              type: object
          type: object
      served: true
      storage: true
