version: 2
jobs:
  build:
    machine: true
    environment:
      CHANGE_MINIKUBE_NONE_USER: true
      K8S_VERSION: v1.19.2
      MINIKUBE_VERSION: v1.18.1
      HELM_VERSION: v3.5.3
    steps:
    - checkout
    - run:
        name: Get info
        command: |
          uname -a
          free -h
          cat /etc/os-release
    - run:
        name: Install kubectl
        command: |
          curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/${K8S_VERSION}/bin/linux/amd64/kubectl && \
              chmod +x kubectl && \
              sudo mv kubectl /usr/local/bin/
    - run:
        name: Install helm
        command: |
          curl -# -o helm-${HELM_VERSION}-linux-amd64.tar.gz https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz && \
              tar -xzf helm-${HELM_VERSION}-linux-amd64.tar.gz && \
              chmod +x linux-amd64/helm && \
              sudo mv linux-amd64/helm /usr/local/bin/
    - run:
        name: Helm init
        command: |
          helm init
          sleep 30
    - run:
        name: Helm lint
        command: |
          helm lint filebeat/
