
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: {{ .Values.collector.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": hook-failed, before-hook-creation
  labels:
    {{- include "logzio-otel-operator.labels" . | nindent 4 }}
    "app.kubernetes.io/managed-by": "opentelemetry-operator"
spec:
  nodeSelector: 
  {{ .Values.collector.nodeSelector | toYaml | nindent 4}}
  image: "{{ .Values.collector.image.repository}}:{{ .Values.collector.image.tag}}"
  imagePullPolicy: {{ .Values.collector.image.pullPolicy }}
  upgradeStrategy: {{ .Values.collector.upgradeStrategy }}
  mode: deployment # This configuration is omittable.
  config: 
    {{- include "logzio-otel-operator.collector-config" . | toYaml | nindent 4 -}}