# Default values for prometheus-alerts-migrator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: ""
nameOverride: ""

replicaCount: 1

image:
  repository: logzio/prometheus-alerts-migrator
  pullPolicy: IfNotPresent
  tag: "v1.0.0"

serviceAccount:
  create: true
  annotations: {}
  name: ""

secret:
  create: true
  name: logzio-api-token

config:
  configMapAnnotation: "prometheus.io/kube-rules"
  logzioAPIToken: ""
  logzioAPIURL: "https://api.logz.io/"
  rulesDS: ""
  env_id: "my-env"
  workerCount: 2

rbac:
  rules:
    - apiGroups: [""]
      resources: ["configmaps"]
      verbs: ["get", "list", "watch"]

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}
